/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.4.2/userguide/building_java_projects.html
 */


group = "com.github.navikt"
version = properties["version"] ?: "local-build"

val packageName = "ia-felles"
val jvmTarget = 1.8 // java 8

repositories {
    maven("https://jitpack.io")
    maven("https://packages.confluent.io/maven/")
    mavenCentral()
}

plugins {
    id("org.jetbrains.kotlin.jvm") version "1.5.31"
    `java-library`
    `maven-publish`

}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}

java {
    sourceCompatibility = JavaVersion.toVersion(jvmTarget)
    targetCompatibility = JavaVersion.toVersion(jvmTarget)
    withSourcesJar()
}

//publishing {
//    publications {
//        maven(MavenPublication) {
//            from components.java
//        }
//    }
//}

publishing {

    publications {

        val repository = "https://github.com/navikt/ia-felles"
        create<MavenPublication>("mavenJava") {
            pom {
                name.set(packageName)
                description.set("Felles definisjoner og modeller for IA-domenenet")
                url.set(repository)

                licenses {
                    license {
                        name.set("MIT License")
                        url.set("https://opensource.org/licenses/MIT")
                    }
                }

                scm {
                    connection.set("scm:git:$repository.git")
                    developerConnection.set("scm:git:$repository.git")
                    url.set(repository)
                }
            }
            from(components["java"])
        }
    }
}

